server:
  port: 0

# 공통 파일
# eureka 서버에게 질의하기 위해 필요하며, 모든 모듈에 공통으로 필요
# defaultZone: http://localhost:8761/eureka/ => eureka 서버의 위치정보 명시
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    # IP 주소를 Eureka에 등록하도록 지정 (10.0.0.1 같은 내부 IP 오탐 방지)
    prefer-ip-address: true
    # 실제 노출할 hostname 명시 (Local 환경)
    hostname: localhost
    # 서비스 주소를 확실하게 규정 (AppName:Host:Port 구조)
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mydb
    username: root
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show_sql: true
  cloud:
    bus:
      enabled: true
    refresh:
      # Eureka 및 DataSource 빈이 busrefresh 시 파기되는 것을 방지
      never-refreshable: >
        com.netflix.discovery.EurekaClient,
        org.springframework.cloud.netflix.eureka.serviceregistry.EurekaAutoServiceRegistration,
        javax.sql.DataSource,
        com.zaxxer.hikari.HikariDataSource
