# 공통 파일
# eureka 서버에게 질의하기 위해 필요하며, 모든 모듈에 공통으로 필요
# defaultZone: http://localhost:8761/eureka/ => eureka 서버의 위치정보 명시
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    # 호스트 이름을 localhost로 완전히 때려 박아 변수 유실을 원천 차단합니다.
    hostname: localhost
    # 런타임에 어떤 포트가 할당되든 시스템 포트를 추적하도록 바인딩합니다.
    non-secure-port: ${server.port}
    # 인스턴스 ID가 공백이 되거나 유실되지 않도록 결합 구조를 단순화합니다.
    instance-id: ${spring.application.name}:${random.uuid}
    
# 3307, admin, port 주의
server:
  # 0으로 세팅하면 spring이 임의 port를 할당(굳이 8081..등으로 관리할 필요없음)
  # eureka에 등록할 때 할당된 임의 port를 알려주고 apigate가 ureka에게 물어보므로 개발자가 port를 관리할 필요가 없다
  port: 0

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mydb
    username: root
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show_sql: true
  cloud:
    bus:
      enabled: true
    # 4. 버스 리프레시가 발생해도 포트 번호와 유레카 인스턴스 정보가 초기화(재생성)되는 것을 차단
    refresh:
      never-refreshable:
        - server.port
        - eureka.instance
