# 공통 파일
# eureka 서버에게 질의하기 위해 필요하며, 모든 모듈에 공통으로 필요
# defaultZone: http://localhost:8761/eureka/ => eureka 서버의 위치정보 명시
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    # 2. 유레카 등록 포트를 0이 아닌 실제 런타임에 바인딩된 포트로 강제 지정
    non-secure-port: ${spring.application.instance_id:${server.port:0}}
    
    # 3. 유레카에서 인식할 고유 ID 설정 (호스트명 + 서비스명 + 랜덤값 또는 실제 포트)
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
    
    # 4. (선택) 상태체크 및 홈 URL 경로에 실제 포트 매핑 보장
    status-page-url-path: ${server.servlet.context-path:}/actuator/info
    health-check-url-path: ${server.servlet.context-path:}/actuator/health
    
# 3307, admin, port 주의
server:
  # 0으로 세팅하면 spring이 임의 port를 할당(굳이 8081..등으로 관리할 필요없음)
  # eureka에 등록할 때 할당된 임의 port를 알려주고 apigate가 ureka에게 물어보므로 개발자가 port를 관리할 필요가 없다
  port: 0

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mydb
    username: root
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show_sql: true
  cloud:
    bus:
      enabled: true
    refresh:
      never-refreshable:
        - server.port # 1. 포트 변수가 refresh로 초기화되는 것을 절대 차단
